# Generated by Django 3.2.21 on 2023-12-10 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoDjango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('numero_de_modulos', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('data', models.DateTimeField(default=datetime.datetime(2023, 12, 10, 16, 36, 42, 837065), verbose_name='Publicado em')),
            ],
        ),
    ]
