# Generated by Django 3.2.21 on 2023-12-10 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetodjango',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 18, 51, 8, 6622), verbose_name='Publicado em'),
        ),
    ]
